[Icon Theme]
Name=Bromigos
Comment=Breeze Dark with phosphor folders
Inherits=breeze-dark,breeze,hicolor
Directories=places/16,places/22,places/24,places/32,places/48,places/64,places/96

[places/16]
Size=16
Context=Places
Type=Fixed
MinSize=16

[places/22]
Size=22
Context=Places
Type=Fixed

[places/24]


[places/32]
Size=32
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
Type=Fixed

[places/64]
Size=64
Context=Places
Type=Fixed

[places/96]
Size=96
Context=Places
Type=Scalable
MinSize=96
MaxSize=256

